name: .NET Core CI/CD Pipeline

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore PR6.sln

    - name: Build solution
      run: dotnet build PR6.sln --no-restore --configuration Release

    - name: Run xUnit Tests
      run: dotnet test TestProject/TestProject.csproj --no-build --configuration Release --verbosity normal --logger "trx;LogFileName=test_results.trx"
